"use client";

import React, { createContext, useContext, useState, useEffect } from "react";
import { useAuth } from "./auth-context";

type Language = "en" | "hi" | "mr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    hero_title: "Master Your Future",
    hero_with: "With",
    hero_excellence: "Excellence",
    hero_desc: "Discover a world of knowledge with expert-led courses. Level up your skills and join a community of heroes!",
    btn_quest: "Start Your Quest",
    btn_challenge: "Enter Challenge Zone",
    challenge_title: "The Challenge Zone",
    challenge_desc: "Level up by completing quizzes and practicing your code!",
    prove_skills: "Prove Your",
    skills: "Skills",
    choose_path: "Choose Your Path",
    btn_start: "Start",
    btn_exit: "Exit",
    btn_back: "Back",
    finding_opponent: "Finding Opponent...",
    code_playground: "Code Playground",
    run_magic: "Run Magic",
    accuracy: "Accuracy",
    exp_earned: "Credits Earned",
    global_rank: "Global Rank",
    try_again: "Try Again",
    back_to_challenges: "Back to Challenges",
    challenge_complete: "Challenge Complete!",
    exit_challenge: "Exit Challenge",
    question: "Question",
    of: "of",
    path_title: "Pick Your Path!",
    path_desc: "What kind of creator do you want to be today? Choose an adventure!",
    cat_python: "Python",
    cat_java: "Java",
    cat_cpp: "C++",
    cat_c: "C Language",
    cat_js: "JavaScript",
    cat_ds: "Data Science",
    cat_aiml: "AI & ML",
    cat_web: "Web Dev",
    cat_3d: "3D Printing",
    cat_robotics: "Robotics",
    cat_electronics: "Electronics",
    cat_drone: "Drone",
    courses_text: "courses",
    explore: "Explore",
    featured_title: "Featured Courses",
    featured_desc: "Learn from the best instructors around the world",
    view_all: "View All Courses",
    reviews: "reviews",
    nav_dashboard: "Dashboard",
    nav_all_courses: "Elite Courses",
    nav_challenge_zone: "Challenge Zone",
    nav_attendance: "Attendance Records",
    nav_submissions: "Submissions Hub",
    nav_offline_centres: "Offline Centres",
    nav_store: "Elite Store",
    nav_profile: "Profile Settings",
    nav_logout: "Logout",
    att_title: "Centre Attendance",
    att_present: "Mark Present",
    att_stats: "Daily Presence",
    att_record: "Centre Statistics",
    sub_title: "Submissions Hub",
    sub_assignments: "Assignments",
    sub_reports: "Progress Reports",
    sub_upload: "Upload Submission",
    sub_drag: "Drag and drop your elite work here",
    sub_submit: "Finalize Submission",
    dash_welcome: "Level up,",
    dash_visionary: "Elite!",
    dash_identity: "Identity Verified",
    dash_stats_desc: "You have {missions} active missions and {rewards} uncollected rewards.",
    dash_resume: "Resume Learning",
    dash_claim: "Claim Rewards",
    stat_streak: "Day Streak",
    stat_xp: "Elite Credits",
    act_search: "Search for courses...",
    act_battle: "Skill Duel",
    act_battle_desc: "Challenge others in real-time coding",
    act_quests: "Daily Tasks",
    act_quests_desc: "Complete goals for extra credits",
    act_events: "Live Events",
    act_events_desc: "Join our upcoming workshops",
    act_store_desc: "Redeem credits for rewards",
    sec_mission: "Current Learning",
    sec_library: "Knowledge Base",
    sec_performance: "Academic Progress",
    sec_visionaries: "Top Performers",
    stat_enrolled: "Enrolled",
    stat_completed: "Completed",
    stat_hours: "Hours Spent",
    stat_mentorship: "Elite Mentorship",
    act_mentor: "Become a Mentor",
    act_mentor_desc: "Help peers & earn extra credits",
    act_daily_missions: "Daily Missions",
    act_command_centre: "Command Centre",
    act_confirm_close: "Confirm & Close",
    act_recommended: "Recommended for You",
    act_enroll_now: "Enroll Now",
    act_view_leaderboard: "View Full Leaderboard",
    banner_text: "Join the Elite Community today!",
    banner_register: "Register Now",
    nav_more: "More",
    nav_login: "Login",
    nav_signup: "Join Elite",
    att_auth_active: "Instructor Authorization Active",
    att_mark_presence: "Mark Presence.",
    att_mark_desc: "Enter your session code to verify your identity.",
    att_secured: "PRESENCE SECURED",
    att_total_present: "Total Present",
    att_compliance: "Elite Compliance",
    att_compliance_score: "Compliance Score",
    att_compliance_desc: "Daily session codes prevent remote marking, ensuring authenticity.",
    att_anti_cheat: "Anti-Cheat Active",
    att_session_code: "Session Code:",
    att_required: "REQUIRED",
    att_identity_match: "Identity Match:",
    att_ready: "READY",
    att_auth_required: "Authorization Required",
    att_photo_verify: "Photo Verification",
    att_presence_confirmed: "Presence Confirmed",
    att_code_desc: "Enter the 6-digit session code provided by your instructor.",
    att_photo_desc: "Please take a clear selfie to finalize your attendance.",
    att_log_success: "Your elite presence has been securely logged.",
    att_verify_btn: "Verify Session Code",
    att_camera_blocked: "Camera Blocked. Please enable access in browser settings.",
    att_retry: "Retry",
    att_capture_proof: "Capture Selfie Proof",
    att_retake: "Retake",
    att_confirm_log: "Confirm & Log",
    att_logged: "Attendance Logged",
    att_continue_dash: "Continue to Dashboard",
    course_unlimited: "UNLIMITED KNOWLEDGE",
    course_masterclasses: "Elite Masterclasses.",
    course_hero_desc: "Discover world-class technical education, project-based and free forever. Curated for tomorrow's visionaries.",
    course_search_placeholder: "Search for elite curriculums...",
    course_search_btn: "SEARCH",
    course_explore: "Explore",
    course_search_title: "Search:",
    course_master_skills: "Master your skills in",
    course_master_desc: "with our industry-leading technical tracks.",
    course_showing_results: "Showing curated results for",
    course_across_elite: "across our elite programs.",
    centre_hero_badge: "ELITE CAMPUS NETWORK",
    centre_hero_title: "AIR G Innovation Labs.",
    centre_hero_desc: "Step into the future of learning at our state-of-the-art AIR G Innovation Labs. From advanced robotics to AI mastery, we bring the global technical revolution to your local campus.",
    centre_btn_nearest: "Find Nearest Centre",
    centre_btn_virtual: "Book a Virtual Tour",
    centre_trust_title1: "Certified Spaces",
    centre_trust_desc1: "Industry-standard lab facilities.",
    centre_trust_title2: "High-Speed Access",
    centre_trust_desc2: "Gigabit internet & elite hardware.",
    centre_trust_title3: "Global Curriculum",
    centre_trust_desc3: "Same quality everywhere.",
    centre_network_title: "Our Campus Network",
    centre_network_desc: "Each AIR G campus is designed to be an innovation hub, equipped with the latest technology and expert faculty.",
    centre_mon_fri: "Mon - Fri",
    centre_btn_directions: "Get Directions",
    centre_cta_title: "Wanna work together?",
    centre_cta_desc: "Put your email and we will contact you to discuss your technical future.",
    centre_input_placeholder: "Your elite email",
    centre_btn_contact: "Contact Me",
    store_hero_badge: "AIR G ELITE GEAR",
    store_hero_title: "Get your AIR G Merchandise Now.",
    store_hero_desc: "Exclusive AIR G apparel and gear designed for the modern technical visionary. Show your elite status with pride.",
    store_btn_explore: "Explore Collections",
    store_feat_title1: "Premium Quality",
    store_feat_desc1: "Sourced for durability and design.",
    store_feat_title2: "Global Shipping",
    store_feat_desc2: "Delivered to your campus or home.",
    store_feat_title3: "Secure Checkout",
    store_feat_desc3: "100% safe & encrypted payments.",
    store_main_title: "Official Merchandise",
    store_main_desc: "Upgrade your developer toolkit with our official gear.",
    store_btn_add: "Add to Gear",
    store_checkout_title: "Elite Checkout",
    store_redeem_credits: "Redeem Elite Credits",
    store_available: "Available",
    store_apply_credits: "Apply Credits",
    store_save: "Save",
    store_subtotal: "Subtotal",
    store_discount: "Credit Discount",
    store_total: "Total",
    store_btn_purchase: "Complete Purchase",
    store_newsletter_title: "Get Exclusive Drops Right in Your Inbox.",
    store_newsletter_desc: "Join the elite circle and be the first to know about new merchandise, tech releases, and limited edition learning kits.",
    store_btn_subscribe: "Subscribe",
    sub_hero_title: "Project Submissions.",
    sub_hero_desc: "Submit your technical projects and track your progress reports. Our instructors review your work for elite certification standards.",
    sub_status_active: "Active",
    sub_status_verified: "Verified",
    sub_mission: "Assignment Mission",
    sub_deadline: "Deadline:",
    sub_status_submitted: "Submitted",
    sub_status_mastered: "Mastered",
    sub_view_submission: "View Submission",
    sub_generated_on: "Generated on",
    sub_vault_title: "Submission Vault",
    sub_encrypting: "Encrypting Work...",
    sub_finalized: "Submission Finalized",
    sub_ready: "Ready to Finalize",
    sub_file_warning: "Ensure all files are in PDF or ZIP format. Max size 50MB per submission.",
    sub_receipt_title: "SUBMISSION RECEIPT",
    sub_receipt_file: "Encrypted File",
    sub_receipt_grade: "Trainer Grade",
    sub_receipt_feedback: "Elite Trainer Feedback",
    sub_receipt_pending_desc: "Your submission is in the queue. Our elite instructors will review your technical architecture and design patterns within 24-48 hours.",
    sub_receipt_reviewed_desc: "Exceptional implementation of Next.js server components. Your state management logic is industry-standard. Excellent work on the UI fidelity.",
    sub_btn_close_receipt: "Close Receipt",
    sub_no_file_error: "No File Selected",
    sub_no_file_desc: "Please choose a file or drag it into the vault.",
    sub_success_title: "Submission Successful!",
    sub_success_desc: "has been encrypted and sent for review.",
    sub_file_info_title: "File Selected",
    sub_file_info_desc: "is ready for submission.",
    plans_hero_badge: "CHOOSE YOUR IDENTITY",
    plans_hero_title: "Become an AI Pro.",
    plans_hero_desc: "Select a membership tier that aligns with your professional vision. Join thousands of AIR G Students today.",
    plans_popular: "MOST POPULAR",
    plans_why_join: "Why join as an AIR G Student?",
    plans_feature1_label: "Fast-Track Learning",
    plans_feature1_desc: "Project-based curriculum",
    plans_feature2_label: "Global Status",
    plans_feature2_desc: "Recognized certifications",
    plans_feature3_label: "Expert Network",
    plans_feature3_desc: "Direct instructor access",
    plans_feature4_label: "Career Security",
    plans_feature4_desc: "Direct placement support",
    plans_testimonial: "Becoming an AIR G Student was the single best decision for my tech career. The 1v1 battles and certs opened doors I never thought possible.",
    plans_testimonial_author: "Sameer K., Software Engineer @ TechGiant",
    nav_student_portal: "Student Portal",
    nav_become_student: "Become an AIR G Student",
    nav_join_now: "Join Now",
  },
  hi: {
    hero_title: "अपना भविष्य संवारें",
    hero_with: "साथ",
    hero_excellence: "उत्कृष्टता",
    hero_desc: "विशेषज्ञों द्वारा संचालित पाठ्यक्रमों के साथ ज्ञान की दुनिया की खोज करें। अपने कौशल को बढ़ाएं और नायकों के समुदाय में शामिल हों!",
    btn_quest: "अपनी खोज शुरू करें",
    btn_challenge: "चुनौती क्षेत्र में प्रवेश करें",
    challenge_title: "चुनौती क्षेत्र",
    challenge_desc: "क्विज़ पूरा करके और अपने कोड का अभ्यास करके लेवल बढ़ाएं!",
    prove_skills: "अपनी स्किल्स",
    skills: "साबित करें",
    choose_path: "अपना रास्ता चुनें",
    btn_start: "शुरू करें",
    btn_exit: "बाहर निकलें",
    btn_back: "पीछे",
    finding_opponent: "प्रतिद्वंद्वी की तलाश है...",
    code_playground: "कोड प्लेग्राउंड",
    run_magic: "जादू चलाएं",
    accuracy: "सटीकता",
    exp_earned: "क्रेडिट्स अर्जित",
    global_rank: "वैश्विक रैंक",
    try_again: "फिर से प्रयास करें",
    back_to_challenges: "चुनौतियों पर वापस जाएं",
    challenge_complete: "चुनौती पूरी हुई!",
    exit_challenge: "चुनौती से बाहर निकलें",
    question: "प्रश्न",
    of: "का",
    path_title: "अपना रास्ता चुनें!",
    path_desc: "आज आप किस तरह के निर्माता बनना चाहते हैं? एक साहसिक कार्य चुनें!",
    cat_python: "पायथन",
    cat_java: "जावा",
    cat_cpp: "C++",
    cat_c: "C भाषा",
    cat_js: "जावास्क्रिप्ट",
    cat_ds: "डेटा साइंस",
    cat_aiml: "AI और ML",
    cat_web: "वेब डेवलपमेंट",
    cat_3d: "3D प्रिंटिंग",
    cat_robotics: "रोबोटिक्स",
    cat_electronics: "इलेक्ट्रॉनिक्स",
    cat_drone: "ड्रोन",
    courses_text: "कोर्स",
    explore: "एक्सप्लोर करें",
    featured_title: "विशेष पाठ्यक्रम",
    featured_desc: "दुनिया भर के सर्वश्रेष्ठ प्रशिक्षकों से सीखें",
    view_all: "सभी पाठ्यक्रम देखें",
    reviews: "समीक्षाएं",
    nav_dashboard: "डैशबोर्ड",
    nav_all_courses: "एलीट कोर्सेज",
    nav_challenge_zone: "चुनौती क्षेत्र",
    nav_attendance: "उपस्थिति रिकॉर्ड",
    nav_submissions: "सबमिशन हब",
    nav_offline_centres: "ऑफलाइन केंद्र",
    nav_store: "एलीट स्टोर",
    nav_profile: "प्रोफ़ाइल सेटिंग्स",
    nav_logout: "लॉगआउट",
    att_title: "केंद्र उपस्थिति",
    att_present: "उपस्थिति दर्ज करें",
    att_stats: "दैनिक उपस्थिति",
    att_record: "केंद्र सांख्यिकी",
    sub_title: "सबमिशन हब",
    sub_assignments: "असाइनमेंट",
    sub_reports: "प्रगति रिपोर्ट",
    sub_upload: "सबमिशन अपलोड करें",
    sub_drag: "अपना एलीट कार्य यहाँ ड्रैग और ड्रॉप करें",
    sub_submit: "सबमिशन फाइनल करें",
    dash_welcome: "लेवल अप,",
    dash_visionary: "एलीट!",
    dash_identity: "पहचान सत्यापित",
    dash_stats_desc: "आपके पास {missions} सक्रिय मिशन और {rewards} अनकलेक्टेड रिवार्ड्स हैं।",
    dash_resume: "सीखना जारी रखें",
    dash_claim: "रिवार्ड्स क्लेम करें",
    stat_streak: "डे स्ट्रीक",
    stat_xp: "एलीट क्रेडिट्स",
    act_search: "कोर्स खोजें...",
    act_battle: "कौशल द्वंद्व",
    act_battle_desc: "रीअल-टाइम कोडिंग में दूसरों को चुनौती दें",
    act_quests: "दैनिक कार्य",
    act_quests_desc: "अतिरिक्त क्रेडिट के लिए लक्ष्य पूरे करें",
    act_events: "लाइव इवेंट्स",
    act_events_desc: "हमारी आगामी कार्यशालाओं में शामिल हों",
    act_store_desc: "रिवार्ड्स के लिए क्रेडिट रिडीम करें",
    sec_mission: "वर्तमान शिक्षा",
    sec_library: "ज्ञान का भंडार",
    sec_performance: "शैक्षिक प्रगति",
    sec_visionaries: "शीर्ष प्रदर्शन करने वाले",
    stat_enrolled: "नामांकित",
    stat_completed: "पूरा किया",
    stat_hours: "बिताए गए घंटे",
    stat_mentorship: "एलीट मेंटरशिप",
    act_mentor: "मेंटर बनें",
    act_mentor_desc: "साथियों की मदद करें और अतिरिक्त क्रेडिट कमाएं",
    act_daily_missions: "दैनिक मिशन",
    act_command_centre: "कमांड सेंटर",
    act_confirm_close: "पुष्टि करें और बंद करें",
    act_recommended: "आपके लिए अनुशंसित",
    act_enroll_now: "अभी नामांकन करें",
    act_view_leaderboard: "पूरी लीडरबोर्ड देखें",
    banner_text: "आज ही एलीट समुदाय में शामिल हों!",
    banner_register: "अभी रजिस्टर करें",
    nav_more: "अधिक",
    nav_login: "लॉगिन",
    nav_signup: "एलीट में शामिल हों",
    att_auth_active: "प्रशिक्षक प्राधिकरण सक्रिय",
    att_mark_presence: "उपस्थिति दर्ज करें",
    att_mark_desc: "अपनी पहचान सत्यापित करने के लिए अपना सत्र कोड दर्ज करें।",
    att_secured: "उपस्थिति सुरक्षित",
    att_total_present: "कुल उपस्थित",
    att_compliance: "एलीट अनुपालन",
    att_compliance_score: "अनुपालन स्कोर",
    att_compliance_desc: "दैनिक सत्र कोड रिमोट मार्किंग को रोकते हैं, प्रामाणिकता सुनिश्चित करते हैं।",
    att_anti_cheat: "एंटी-चीट सक्रिय",
    att_session_code: "सत्र कोड:",
    att_required: "आवश्यक",
    att_identity_match: "पहचान मिलान:",
    att_ready: "तैयार",
    att_auth_required: "प्राधिकरण आवश्यक",
    att_photo_verify: "फोटो सत्यापन",
    att_presence_confirmed: "उपस्थिति की पुष्टि",
    att_code_desc: "अपने प्रशिक्षक द्वारा प्रदान किया गया 6-अंकीय सत्र कोड दर्ज करें।",
    att_photo_desc: "अपनी उपस्थिति को अंतिम रूप देने के लिए कृपया एक स्पष्ट सेल्फी लें।",
    att_log_success: "आपकी एलीट उपस्थिति सुरक्षित रूप से लॉग की गई है।",
    att_verify_btn: "सत्र कोड सत्यापित करें",
    att_camera_blocked: "कैमरा ब्लॉक किया गया। कृपया ब्राउज़र सेटिंग्स में एक्सेस सक्षम करें।",
    att_retry: "पुनः प्रयास करें",
    att_capture_proof: "सेल्फी प्रूफ लें",
    att_retake: "फिर से लें",
    att_confirm_log: "पुष्टि करें और लॉग करें",
    att_logged: "उपस्थिति लॉग की गई",
    att_continue_dash: "डैशबोर्ड पर जारी रखें",
    course_unlimited: "असीमित ज्ञान",
    course_masterclasses: "एलीट मास्टरक्लासेस।",
    course_hero_desc: "विश्व स्तरीय तकनीकी शिक्षा की खोज करें, जो प्रोजेक्ट-आधारित और हमेशा के लिए मुफ़्त है। कल के दूरदर्शी लोगों के लिए क्यूरेट की गई।",
    course_search_placeholder: "एलीट पाठ्यक्रम खोजें...",
    course_search_btn: "खोजें",
    course_explore: "एक्सप्लोर करें",
    course_search_title: "खोज:",
    course_master_skills: "अपने कौशल को मास्टर करें",
    course_master_desc: "हमारे उद्योग-अग्रणी तकनीकी ट्रैक्स के साथ।",
    course_showing_results: "क्यूरेटेड परिणाम दिखा रहे हैं",
    course_across_elite: "हमारे एलीट कार्यक्रमों में।",
    centre_hero_badge: "एलीट कैंपस नेटवर्क",
    centre_hero_title: "AIR G इनोवेशन लैब्स।",
    centre_hero_desc: "हमारी अत्याधुनिक AIR G इनोवेशन लैब्स में सीखने के भविष्य में कदम रखें। उन्नत रोबोटिक्स से लेकर AI महारत तक, हम वैश्विक तकनीकी क्रांति को आपके स्थानीय परिसर में लाते हैं।",
    centre_btn_nearest: "निकटतम केंद्र खोजें",
    centre_btn_virtual: "वर्चुअल टूर बुक करें",
    centre_trust_title1: "प्रमाणित स्थान",
    centre_trust_desc1: "उद्योग-मानक लैब सुविधाएं।",
    centre_trust_title2: "हाई-स्पीड एक्सेस",
    centre_trust_desc2: "गीगाबिट इंटरनेट और एलीट हार्डवेयर।",
    centre_trust_title3: "वैश्विक पाठ्यक्रम",
    centre_trust_desc3: "हर जगह समान गुणवत्ता।",
    centre_network_title: "हमारा कैंपस नेटवर्क",
    centre_network_desc: "प्रत्येक एआईआर जी कैंपस को एक नवाचार केंद्र के रूप में डिज़ाइन किया गया है, जो नवीनतम तकनीक और विशेषज्ञ संकाय से सुसज्जित है।",
    centre_mon_fri: "सोम - शुक्र",
    centre_btn_directions: "दिशा-निर्देश प्राप्त करें",
    centre_cta_title: "साथ काम करना चाहते हैं?",
    centre_cta_desc: "अपना ईमेल डालें और हम आपके तकनीकी भविष्य पर चर्चा करने के लिए आपसे संपर्क करेंगे।",
    centre_input_placeholder: "आपका एलीट ईमेल",
    centre_btn_contact: "मुझसे संपर्क करें",
    store_hero_badge: "एआईआर जी एलीट गियर",
    store_hero_title: "अपना AIR G मर्चेंडाइज अभी प्राप्त करें।",
    store_hero_desc: "आधुनिक तकनीकी दूरदर्शी के लिए डिज़ाइन किए गए एक्सक्लूसिव AIR G परिधान और गियर। गर्व के साथ अपनी एलीट स्थिति दिखाएं।",
    store_btn_explore: "संग्रह देखें",
    store_feat_title1: "प्रीमियम गुणवत्ता",
    store_feat_desc1: "स्थायित्व और डिज़ाइन के लिए स्रोत।",
    store_feat_title2: "वैश्विक शिपिंग",
    store_feat_desc2: "आपके कैंपस या घर पर पहुँचाया गया।",
    store_feat_title3: "सुरक्षित चेकआउट",
    store_feat_desc3: "100% सुरक्षित और एन्क्रिप्टेड भुगतान।",
    store_main_title: "आधिकारिक मर्चेंडाइज",
    store_main_desc: "हमारे आधिकारिक गियर के साथ अपने डेवलपर टूलकिट को अपग्रेड करें।",
    store_btn_add: "गियर में जोड़ें",
    store_checkout_title: "एलीट चेकआउट",
    store_redeem_credits: "एलीट क्रेडिट रिडीम करें",
    store_available: "उपलब्ध",
    store_apply_credits: "क्रेडिट लागू करें",
    store_save: "बचत",
    store_subtotal: "उप-योग",
    store_discount: "क्रेडिट छूट",
    store_total: "कुल",
    store_btn_purchase: "खरीद पूरी करें",
    store_newsletter_title: "सीधे अपने इनबॉक्स में एक्सक्लूसिव ड्रॉप्स प्राप्त करें।",
    store_newsletter_desc: "एलीट सर्कल में शामिल हों और नए मर्चेंडाइज, टेक रिलीज और सीमित संस्करण लर्निंग किट के बारे में जानने वाले पहले व्यक्ति बनें।",
    store_btn_subscribe: "सब्सक्राइब करें",
    sub_hero_title: "प्रोजेक्ट सबमिशन।",
    sub_hero_desc: "अपने तकनीकी प्रोजेक्ट जमा करें और अपनी प्रगति रिपोर्ट ट्रैक करें। हमारे प्रशिक्षक एलीट प्रमाणन मानकों के लिए आपके कार्य की समीक्षा करते हैं।",
    sub_status_active: "सक्रिय",
    sub_status_verified: "सत्यापित",
    sub_mission: "असाइनमेंट मिशन",
    sub_deadline: "समय सीमा:",
    sub_status_submitted: "जमा किया गया",
    sub_status_mastered: "मास्टर्ड",
    sub_view_submission: "सबमिशन देखें",
    sub_generated_on: "जनरेट किया गया",
    sub_vault_title: "सबमिशन वॉल्ट",
    sub_encrypting: "कार्य एन्क्रिप्ट किया जा रहा है...",
    sub_finalized: "सबमिशन अंतिम रूप दिया गया",
    sub_ready: "अंतिम रूप देने के लिए तैयार",
    sub_file_warning: "सुनिश्चित करें कि सभी फाइलें पीडीएफ या जिप प्रारूप में हों। प्रति सबमिशन अधिकतम आकार 50 एमबी।",
    sub_receipt_title: "सबमिशन रसीद",
    sub_receipt_file: "एन्क्रिप्टेड फाइल",
    sub_receipt_grade: "प्रशिक्षक ग्रेड",
    sub_receipt_feedback: "एलीट प्रशिक्षक फीडबैक",
    sub_receipt_pending_desc: "आपका सबमिशन कतार में है। हमारे एलीट प्रशिक्षक 24-48 घंटों के भीतर आपके तकनीकी आर्किटेक्चर और डिज़ाइन पैटर्न की समीक्षा करेंगे।",
    sub_receipt_reviewed_desc: "Next.js सर्वर घटकों का असाधारण कार्यान्वयन। आपका स्टेट मैनेजमेंट लॉजिक उद्योग-मानक है। यूआई फिडेलिटी पर उत्कृष्ट कार्य।",
    sub_btn_close_receipt: "रसीद बंद करें",
    sub_no_file_error: "कोई फ़ाइल चुनी नहीं गई",
    sub_no_file_desc: "कृपया एक फ़ाइल चुनें या उसे वॉल्ट में ड्रैग करें।",
    sub_success_title: "सबमिशन सफल!",
    sub_success_desc: "एन्क्रिप्ट किया गया है और समीक्षा के लिए भेजा गया है।",
    sub_file_info_title: "फ़ाइल चुनी गई",
    sub_file_info_desc: "सबमिशन के लिए तैयार है।",
    plans_hero_badge: "अपनी पहचान चुनें",
    plans_hero_title: "एआई प्रो बनें।",
    plans_hero_desc: "एक सदस्यता स्तर चुनें जो आपके पेशेवर विजन के साथ मेल खाता हो। आज ही हजारों एआईआर जी छात्रों में शामिल हों।",
    plans_popular: "सबसे लोकप्रिय",
    plans_why_join: "एआईआर जी छात्र के रूप में क्यों शामिल हों?",
    plans_feature1_label: "फास्ट-ट्रैक लर्निंग",
    plans_feature1_desc: "प्रोजेक्ट-आधारित पाठ्यक्रम",
    plans_feature2_label: "वैश्विक स्थिति",
    plans_feature2_desc: "मान्यता प्राप्त प्रमाणपत्र",
    plans_feature3_label: "विशेषज्ञ नेटवर्क",
    plans_feature3_desc: "प्रशिक्षक तक सीधी पहुंच",
    plans_feature4_label: "करियर सुरक्षा",
    plans_feature4_desc: "प्रत्यक्ष प्लेसमेंट सहायता",
    plans_testimonial: "एआईआर जी छात्र बनना मेरे तकनीकी करियर के लिए सबसे अच्छा निर्णय था। 1v1 लड़ाइयों और प्रमाणपत्रों ने ऐसे दरवाजे खोले जो मैंने कभी संभव नहीं सोचे थे।",
    plans_testimonial_author: "समीर के., सॉफ्टवेयर इंजीनियर @ TechGiant",
    nav_student_portal: "छात्र पोर्टल",
    nav_become_student: "एआईआर जी छात्र बनें",
    nav_join_now: "अभी शामिल हों",
  },
  mr: {
    hero_title: "आपले भविष्य घडवा",
    hero_with: "सह",
    hero_excellence: "उत्कृष्टता",
    hero_desc: "तज्ञ-मार्गदर्शित कोर्सेससह ज्ञानाचे जग शोधा. आपली कौशल्ये सुधारा आणि वीरांच्या समुदायात सामील व्हा!",
    btn_quest: "तुमचा शोध सुरू करा",
    btn_challenge: "चॅलेंज झोनमध्ये प्रवेश करा",
    challenge_title: "चॅलेंज झोन",
    challenge_desc: "क्विझ पूर्ण करून आणि कोडचा सराव करून लेव्हल वाढवा!",
    prove_skills: "तुमची कौशल्ये",
    skills: "सिद्ध करा",
    choose_path: "तुमचा मार्ग निवडा",
    btn_start: "सुरू करा",
    btn_exit: "बाहेर पडा",
    btn_back: "मागे",
    finding_opponent: "प्रतिस्पर्धी शोधत आहे...",
    code_playground: "कोड प्लेग्राउंड",
    run_magic: "जादू चालवा",
    accuracy: "अचूकता",
    exp_earned: "क्रेडिट्स मिळवले",
    global_rank: "जागतिक रँक",
    try_again: "पुन्हा प्रयत्न करा",
    back_to_challenges: "आव्हानांकडे परत जा",
    challenge_complete: "चॅलेंज पूर्ण झाले!",
    exit_challenge: "बाहेर पडा",
    question: "प्रश्न",
    of: "पैकी",
    path_title: "तुमचा मार्ग निवडा!",
    path_desc: "आज तुम्हाला कोणत्या प्रकारचे निर्माते व्हायचे आहे? एक साहस निवडा!",
    cat_python: "पायथन",
    cat_java: "जावा",
    cat_cpp: "C++",
    cat_c: "C भाषा",
    cat_js: "जावास्क्रिप्ट",
    cat_ds: "डेटा सायन्स",
    cat_aiml: "AI आणि ML",
    cat_web: "वेब डेव्हलपमेंट",
    cat_3d: "3D प्रिंटिंग",
    cat_robotics: "रोबोटिक्स",
    cat_electronics: "इलेक्ट्रॉनिक्स",
    cat_drone: "ड्रोन",
    courses_text: "कोर्सेस",
    explore: "एक्सप्लोर करा",
    featured_title: "वैशिष्ट्यीकृत कोर्सेस",
    featured_desc: "जगभरातील सर्वोत्तम प्रशिक्षकांकडून शिका",
    view_all: "सर्व कोर्सेस पहा",
    reviews: "पुनरावलोकने",
    nav_dashboard: "डॅशबोर्ड",
    nav_all_courses: "एलीट कोर्सेस",
    nav_challenge_zone: "चॅलेंज झोन",
    nav_attendance: "उपस्थिती रेकॉर्ड",
    nav_submissions: "सबमिशन हब",
    nav_offline_centres: "ऑफलाइन केंद्रे",
    nav_store: "एलीट स्टोअर",
    nav_profile: "प्रोफाइल सेटिंग्ज",
    nav_logout: "लॉगआउट",
    att_title: "केंद्र उपस्थिती",
    att_present: "उपस्थिती नोंदवा",
    att_stats: "दैनिक उपस्थिती",
    att_record: "केंद्र सांख्यिकी",
    sub_title: "सबमिशन हब",
    sub_assignments: "असाइनमेंट्स",
    sub_reports: "प्रगती अहवाल",
    sub_upload: "सबमिशन अपलोड करा",
    sub_drag: "तुमचे एलीट काम येथे ड्रॅग आणि ड्रॉप करा",
    sub_submit: "सबमिशन फायनल करा",
    dash_welcome: "लेव्हल अप,",
    dash_visionary: "एलीट!",
    dash_identity: "ओळख सत्यापित",
    dash_stats_desc: "तुमच्याकडे {missions} सक्रिय मिशन आणि {rewards} न मिळालेले रिवॉर्ड्स आहेत.",
    dash_resume: "शिकणे सुरू ठेवा",
    dash_claim: "रिवॉर्ड्स मिळवा",
    stat_streak: "डे स्ट्रीक",
    stat_xp: "एलीट क्रेडिट्स",
    act_search: "कोर्सेस शोधा...",
    act_battle: "कौशल द्वंद्व",
    act_battle_desc: "रीअल-टाइम कोडिंगमध्ये इतरांना आव्हान द्या",
    act_quests: "दैनिक कार्ये",
    act_quests_desc: "अतिरिक्त क्रेडिटसाठी ध्येये पूर्ण करा",
    act_events: "लाइव इव्हेंट्स",
    act_events_desc: "आमच्या आगामी कार्यशाळांमध्ये सामील व्हा",
    act_store_desc: "रिवॉर्ड्ससाठी क्रेडिट रिडीम करा",
    sec_mission: "सध्याचे शिक्षण",
    sec_library: "ज्ञानाचा साठा",
    sec_performance: "शैक्षणिक प्रगती",
    sec_visionaries: "शीर्ष कामगिरी करणारे",
    sec_leaderboard: "लीडरबोर्ड",
    stat_enrolled: "नोंदणीकृत",
    stat_completed: "पूर्ण झाले",
    stat_hours: "खर्च केलेले तास",
    stat_mentorship: "एलीट मेंटरशिप",
    act_mentor: "मेंटर बना",
    act_mentor_desc: "सोबत्यांना मदत करा आणि अतिरिक्त क्रेडिट मिळवा",
    act_daily_missions: "दैनिक मिशन",
    act_command_centre: "कमांड सेंटर",
    act_confirm_close: "पुष्टी करा आणि बंद करा",
    act_recommended: "तुमच्यासाठी शिफारस केलेले",
    act_enroll_now: "आता नोंदणी करा",
    act_view_leaderboard: "पूर्ण लीडरबोर्ड पहा",
    act_view_all: "सर्व पहा",
    banner_text: "आजच एलीट समुदायात सामील व्हा!",
    banner_register: "आताच नोंदणी करा",
    nav_more: "अधिक",
    nav_login: "लॉगिन",
    nav_signup: "एलीटमध्ये सामील व्हा",
    att_auth_active: "प्रशिक्षक अधिकृतता सक्रिय",
    att_mark_presence: "उपस्थिती नोंदवा.",
    att_mark_desc: "आपली ओळख सत्यापित करण्यासाठी आपला सत्र कोड प्रविष्ट करा.",
    att_secured: "उपस्थिती सुरक्षित",
    att_total_present: "एकूण उपस्थित",
    att_compliance: "एलीट अनुपालन",
    att_compliance_score: "अनुपालन स्कोअर",
    att_compliance_desc: "दैनिक सत्र कोड रिमोट मार्किंग रोखतात, सत्यता सुनिश्चित करतात.",
    att_anti_cheat: "अँटी-चीट सक्रिय",
    att_session_code: "सत्र कोड:",
    att_required: "आवश्यक",
    att_identity_match: "ओळख जुळणी:",
    att_ready: "तयार",
    att_auth_required: "अधिकृतता आवश्यक",
    att_photo_verify: "फोटो सत्यापन",
    att_presence_confirmed: "उपस्थितीची पुष्टी",
    att_code_desc: "तुमच्या प्रशिक्षकाने दिलेला 6-अंकी सत्र कोड प्रविष्ट करा.",
    att_photo_desc: "तुमची उपस्थिती अंतिम करण्यासाठी कृपया एक स्पष्ट सेल्फी घ्या.",
    att_log_success: "तुमची एलीट उपस्थिती सुरक्षितपणे लॉग केली गेली आहे.",
    att_verify_btn: "सत्र कोड सत्यापित करा",
    att_camera_blocked: "कॅमेरा ब्लॉक केला. कृपया ब्राउझर सेटिंग्जमध्ये प्रवेश सक्षम करा.",
    att_retry: "पुन्हा प्रयत्न करा",
    att_capture_proof: "सेल्फी प्रूफ घ्या",
    att_retake: "पुन्हा घ्या",
    att_confirm_log: "पुष्टी करा आणि लॉग करा",
    att_logged: "उपस्थिती लॉग केली",
    att_continue_dash: "डॅशबोर्डवर जा",
    course_unlimited: "अमर्याद ज्ञान",
    course_masterclasses: "एलीट मास्टरक्लासेस.",
    course_hero_desc: "जागतिक दर्जाचे तांत्रिक शिक्षण शोधा, प्रकल्प-आधारित आणि कायमचे विनामूल्य. उद्याच्या दूरदर्शी लोकांसाठी क्युरेट केलेले.",
    course_search_placeholder: "एलीट अभ्यासक्रम शोधा...",
    course_search_btn: "शोधा",
    course_explore: "एक्सप्लोर करा",
    course_search_title: "शोध:",
    course_master_skills: "आपल्या कौशल्यात प्रभुत्व मिळवा",
    course_master_desc: "आमच्या उद्योगातील अग्रगण्य तांत्रिक ट्रॅकसह.",
    course_showing_results: "साठी क्युरेट केलेले निकाल दर्शवत आहे",
    course_across_elite: "आमच्या एलीट प्रोग्राम्समध्ये.",
    centre_hero_badge: "एलीट कॅम्पस नेटवर्क",
    centre_hero_title: "AIR G इनोव्हेशन लॅब्स.",
    centre_hero_desc: "आमच्या अत्याधुनिक AIR G इनोव्हेशन लॅब्समध्ये शिक्षणाच्या भविष्यात पाऊल टाका. प्रगत रोबोटिक्सपासून ते AI प्रभुत्वापर्यंत, आम्ही जागतिक तांत्रिक क्रांती तुमच्या स्थानिक कॅम्पसमध्ये आणतो.",
    centre_btn_nearest: "जवळचे केंद्र शोधा",
    centre_btn_virtual: "व्हर्च्युअल टूर बुक करा",
    centre_trust_title1: "प्रमाणित जागा",
    centre_trust_desc1: "उद्योग-मानक प्रयोगशाळा सुविधा.",
    centre_trust_title2: "हाय-स्पीड ॲक्सेस",
    centre_trust_desc2: "गिगाबिट इंटरनेट आणि एलीट हार्डवेअर.",
    centre_trust_title3: "जागतिक अभ्यासक्रम",
    centre_trust_desc3: "सर्वत्र समान गुणवत्ता.",
    centre_network_title: "आमचे कॅम्पस नेटवर्क",
    centre_network_desc: "प्रत्येक एआयआर जी कॅम्पस एक नवनिर्मिती केंद्र म्हणून डिझाइन केलेले आहे, जे अत्याधुनिक तंत्रज्ञान आणि तज्ञ विद्याशाखेने सुसज्जित आहे.",
    centre_mon_fri: "सोम - शुक्र",
    centre_btn_directions: "दिशा-निर्देश मिळवा",
    centre_cta_title: "सोबत काम करायचे आहे का?",
    centre_cta_desc: "तुमचा ईमेल टाका आणि आम्ही तुमच्या तांत्रिक भविष्याबद्दल चर्चा करण्यासाठी तुमच्याशी संपर्क साधू.",
    centre_input_placeholder: "तुमचा एलीट ईमेल",
    centre_btn_contact: "माझ्याशी संपर्क साधा",
    store_hero_badge: "एआयआर जी एलीट गियर",
    store_hero_title: "तुमचे AIR G मर्चेंडाइज आत्ताच मिळवा.",
    store_hero_desc: "आधुनिक तांत्रिक दूरदर्शी लोकांसाठी डिझाइन केलेले एक्सक्लूसिव AIR G कपडे आणि गिअर. अभिमानाने तुमची एलीट स्थिती दर्शवा.",
    store_btn_explore: "संग्रह एक्सप्लोर करा",
    store_feat_title1: "प्रीमियम गुणवत्ता",
    store_feat_desc1: "टिकाऊपणा आणि डिझाइनसाठी क्युरेट केलेले.",
    store_feat_title2: "जागतिक शिपिंग",
    store_feat_desc2: "तुमच्या कॅम्पसमध्ये किंवा घरी वितरित.",
    store_feat_title3: "सुरक्षित चेकआउट",
    store_feat_desc3: "100% सुरक्षित आणि कूटबद्ध पेमेंट.",
    store_main_title: "अधिकृत मर्चेंडाइज",
    store_main_desc: "आमच्या अधिकृत गियरसह तुमची डेव्हलपर टूलकिट अपग्रेड करा.",
    store_btn_add: "गियरमध्ये जोडा",
    store_checkout_title: "एलीट चेकआउट",
    store_redeem_credits: "एलीट क्रेडिट्स रिडीम करा",
    store_available: "उपलब्ध",
    store_apply_credits: "क्रेडिट लागू करा",
    store_save: "बचत",
    store_subtotal: "उप-एकूण",
    store_discount: "क्रेडिट सवलत",
    store_total: "एकूण",
    store_btn_purchase: "खरेदी पूर्ण करा",
    store_newsletter_title: "थेट तुमच्या इनबॉक्समध्ये एक्सक्लूसिव्ह ड्रॉप्स मिळवा.",
    store_newsletter_desc: "एलीट सर्कलमध्ये सामील व्हा आणि नवीन मर्चेंडाइज, टेक रिलीज आणि मर्यादित आवृत्ती लर्निंग किटबद्दल जाणून घेणारे पहिले व्हा.",
    store_btn_subscribe: "सब्सक्राइब करा",
    sub_hero_title: "प्रकल्प सबमिशन.",
    sub_hero_desc: "तुमचे तांत्रिक प्रकल्प सबमिट करा आणि तुमचे प्रगती अहवाल ट्रॅक करा. आमचे प्रशिक्षक एलीट प्रमाणन मानकांसाठी तुमच्या कामाचे पुनरावलोकन करतात.",
    sub_status_active: "सक्रिय",
    sub_status_verified: "सत्यापित",
    sub_mission: "असाइनमेंट मिशन",
    sub_deadline: "मुदत:",
    sub_status_submitted: "सबमिट केले",
    sub_status_mastered: "मास्टर्ड",
    sub_view_submission: "सबमिशन पहा",
    sub_generated_on: "वर जनरेट केले",
    sub_vault_title: "सबमिशन वॉल्ट",
    sub_encrypting: "काम एनक्रिप्ट होत आहे...",
    sub_finalized: "सबमिशन फायनल झाले",
    sub_ready: "फायनल करण्यासाठी तयार",
    sub_file_warning: "सर्व फाईल्स PDF किंवा ZIP फॉरमॅटमध्ये असल्याची खात्री करा. प्रति सबमिशन कमाल आकार 50MB.",
    sub_receipt_title: "सबमिशन पावती",
    sub_receipt_file: "एनक्रिप्टेड फाईल",
    sub_receipt_grade: "प्रशिक्षक ग्रेड",
    sub_receipt_feedback: "एलीट प्रशिक्षक अभिप्राय",
    sub_receipt_pending_desc: "तुमचे सबमिशन रांगेत आहे. आमचे एलीट प्रशिक्षक २४-४८ तासांच्या आत तुमच्या तांत्रिक आर्किटेक्चर आणि डिझाइन पॅटर्नचे पुनरावलोकन करतील.",
    sub_receipt_reviewed_desc: "Next.js सर्व्हर घटकांची अपवादात्मक अंमलबजावणी. तुमचे स्टेट मॅनेजमेंट लॉजिक उद्योग-मानक आहे. UI फिडेलिटीवर उत्कृष्ट कार्य.",
    sub_btn_close_receipt: "पावती बंद करा",
    sub_no_file_error: "कोणतीही फाईल निवडली नाही",
    sub_no_file_desc: "कृपया फाईल निवडा किंवा वॉल्टमध्ये ड्रॅग करा.",
    sub_success_title: "सबमिशन यशस्वी!",
    sub_success_desc: "एनक्रिप्ट केले आहे आणि पुनरावलोकनासाठी पाठवले आहे.",
    sub_file_info_title: "फाईल निवडली",
    sub_file_info_desc: "सबमिशनसाठी तयार आहे.",
    plans_hero_badge: "तुमची ओळख निवडा",
    plans_hero_title: "एआय प्रो बना.",
    plans_hero_desc: "तुमच्या व्यावसायिक दृष्टीशी जुळणारा सदस्यत्व स्तर निवडा. आजच हजारो एआयआर जी विद्यार्थ्यांमध्ये सामील व्हा.",
    plans_popular: "सर्वात लोकप्रिय",
    plans_why_join: "एआयआर जी विद्यार्थी म्हणून का सामील व्हावे?",
    plans_feature1_label: "फास्ट-ट्रॅक लर्निंग",
    plans_feature1_desc: "प्रकल्प-आधारित अभ्यासक्रम",
    plans_feature2_label: "जागतिक दर्जा",
    plans_feature2_desc: "मान्यता प्राप्त प्रमाणपत्रे",
    plans_feature3_label: "तज्ञ नेटवर्क",
    plans_feature3_desc: "प्रशिक्षकांपर्यंत थेट पोहोच",
    plans_feature4_label: "करियर सुरक्षा",
    plans_feature4_desc: "थेट प्लेसमेंट सपोर्ट",
    plans_testimonial: "एआयआर जी विद्यार्थी बनणे हा माझ्या टेक करियरसाठी सर्वात चांगला निर्णय होता. 1v1 लढाया आणि प्रमाणपत्रांनी असे दरवाजे उघडले जे मला कधीच शक्य वाटले नव्हते.",
    plans_testimonial_author: "समीर के., सॉफ्टवेअर अभियंता @ TechGiant",
    nav_student_portal: "विद्यार्थी पोर्टल",
    nav_become_student: "एआयआर जी विद्यार्थी बना",
    nav_join_now: "आता सामील व्हा",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);
  const { user, updateProfile } = useAuth();

  // Sync with localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem("app_lang") as Language;
      if (saved && (saved === "en" || saved === "hi" || saved === "mr")) {
        setLanguage(saved);
      }
    } catch (e) {
      console.error("Language sync failed:", e);
    } finally {
      setMounted(true);
    }
  }, []);

  // Sync with User Profile from MongoDB
  useEffect(() => {
    if (user?.preferredLanguage && user.preferredLanguage !== language) {
      setLanguage(user.preferredLanguage as Language);
    }
  }, [user?.preferredLanguage]);

  const handleSetLanguage = async (lang: Language) => {
    setLanguage(lang);
    try {
      localStorage.setItem("app_lang", lang);
      if (user) {
        await updateProfile({ preferredLanguage: lang });
      }
    } catch (e) {
      console.error("Language save failed:", e);
    }
  };

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations["en"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
